config/routes.rb
Rails.application.routes.draw do
  resources :albums
  get 'photos', to: 'albums#user_albums'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user
	has_many_attached :photos
	validates :name, presence: true
	validates :owner, presence: true
	validate :image_type

	private
	def image_type
		if photos.attached? == false
			errors.add(:photos, "are missing.")
		end
		if photos.records.count > 25
			errors.add(:photos, "limit exceeded.")
			photos.purge_later
		end
		photos.each do |photo|
			if photo && !photo.content_type.in?(%w(image/jpeg image/png))
				errors.add(:photo, 'Must be a png a jpeg file')
					photo.purge_later
				end
			end
		end

	end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
   has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def user_albums
      @albums = current_user.albums.paginate(:page => params[:page], :per_page => 6)
   end

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all.order(created_at: :desc)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit( :user_id, :name, :owner, photos:[] )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% albums.each do |album| %>
          <% if !album.blank? %>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <%= link_to (image_tag album.photos.first.variant(resize: "348x225"), class: "card-img-top"), album if album && album.photos %>
                <div class="card-body">
				        <% if !album.owner.blank? %>
                  <p class="lead text-muted">Owner : <%= album.owner %></p>
				        <% end %>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= button_tag(type: 'button', class: "btn btn-sm btn-outline-secondary") do %>
                        <%= link_to 'View', album %>
                      <% end %>
                      <%= button_tag(type: 'button', class: "btn btn-sm btn-outline-secondary") do %>
                        <%= link_to 'Edit', edit_album_path(album) %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form.hidden_field :user_id, :value => current_user.id%>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="form-group">
    <%= form.label :photos %>
    <%= form.file_field :photos, multiple:true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>
<%= render 'form', album: @album %>
<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">PCPL Album</h1>
      <p class="lead text-muted">PCPL allow multiple image gallery for any user , it will enhance the user experience
        and minimize the usage of image space . User can add the image gallery on hyperlink or Image from create
      page.</p>
    </div>
    <div class="col-lg-12 col-md-12 pull-right">
      <%= link_to 'New Album', new_album_path, {class: "btn btn-success"} %>
    </div>
  </section>
  <%= render 'album', albums: @albums %>
</main>

app/views/albums/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h2 class="pcpl-center"> New Album</h2>
    <div class="pcpl-content pcpl-display-container">
      <%= render 'form', album: @album %>
    </div>
    <%= link_to 'Back', albums_path, {class: "btn btn-primary"} %>
  </div>
</div>

app/views/albums/show.html.erb
  <div class="container">
    <div class="pcpl-content pcpl-display-container">
      <% @album.photos.each do |photo| %>
        <%= image_tag (photo.variant(resize: "800x450")), {class: "mySlides", alt: "myiamge", style: "width:100%"} %>
      <% end %>
      <button class="pcpl-button pcpl-black pcpl-display-left" onclick="plusDivs(-1)">&#10094;</button>
      <button class="pcpl-button pcpl-black pcpl-display-right" onclick="plusDivs(1)">&#10095;</button>
    </div>
	<div class="pcpl-content pcpl-display-container">
	<h3 class="pcpl-center"> <%= @album.name if @album && @album.name %> Slideshow</h3><br>
    <h4 class="pcpl-center">By: <%= @album.owner if @album && @album.owner %></h4>
	<div class="pull-right">
    <%= link_to 'Back', albums_path, {class: "btn btn-success"} %>
	</div>
	</div>
  </div>


<script>
    var slideIndex = 1;
    showDivs(slideIndex);
    function plusDivs(n) {
        showDivs(slideIndex += n);
    }
    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) {
            slideIndex = 1
        }
        if (n < 1) {
            slideIndex = x.length
        }
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        x[slideIndex - 1].style.display = "block";
    }
</script>

app/views/albums/user_albums.html.erb
<main role="main">
	<%if !@albums.blank?%>
	<%= render 'album', albums: @albums %>
	<%else%>
	<section class="jumbotron text-center">
		<div class="container">
			<p class="lead text-muted">You haven't created an album Yet. Create one now by following the below Link.</p>
		</div>
		<div class="col-lg-12 col-md-12 pull-right">
			<%= link_to 'New Album', new_album_path, {class: "btn btn-success"} %>
		</div>
	</section>
	<%end%>
</main>
<%= will_paginate @albums %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PCPL</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Bootstrap core CSS -->
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/pcpl.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/"><div class="navbar-brand">Navin's Gallery</div></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <div class="navbar-right">
          <div class="navbar-brand">
            <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> |
            <%= link_to "My albums", "/photos", :class => 'navbar-link' %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </div>
        </div>
      </div>
      <p id="notice"><%= notice %></p>
    </div>
  </nav>
  <div class="jumbotron">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <!-- Bootstrap core JavaScript -->
  <script src="/js/jquery.min.js"></script>
  <script src="/js/bootstrap.bundle.min.js"></script>
</body>
</html>